# Generated by Django 4.1.2 on 2022-10-30 23:38

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtablePersons',
            fields=[
                ('airtable_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('twitter', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('linkedin', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('airtable_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.airtablepersons')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_processed', models.DateTimeField(auto_now=True)),
                ('raw_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.rawcontents')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255, unique=True)),
                ('factors', pgvector.django.VectorField(dimensions=1024, null=True)),
                ('processed_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.processedcontents')),
            ],
        ),
    ]
